Facilities:
  HTTPServer: true
  JSONWs: true
  ServiceErrorManager: true
HTTPServer:
  Address: 0.0.0.0
  Port: 8000
  AccessLogging: true
  AccessLog:
    LogLinePreset: "framework"
ApplicationLogger:
  GlobalLogLevel: INFO
